//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pec2rsrc.rc
//
#define IDOK2                           2
#define IDC_RESTORE_DEFAULTS            3
#define IDS_OK                          14
#define IDS_DOWNLOAD                    15
#define IDS_EXIT                        16
#define IDS_DIALOG_CAPTION              17
#define IDS_GO                          18
#define IDS_CTL_YOURPRODUCTVERSION      19
#define IDS_CTL_NEWPRODUCTVERSION       20
#define IDS_CTL_CANCEL                  21
#define IDS_UPDATE_PROCESS_INFO         22
#define IDS_CTL_STATUS                  23
#define IDS_CTL_CHANGES                 24
#define IDS_AUTO_CHECKBOX_TEXT          25
#define IDS_NEVER_CHECK_TEXT            26
#define IDS_INCLUDE_BETAS_TEXT          27
#define IDS_ALWAYS_AUTO                 28
#define IDS_UPDATE_OPTIONS              29
#define IDD_CODECS                      101
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDS_COLUMN_FILENAME             104
#define IDM_ABOUT                       104
#define IDS_COLUMN_OPTIONS              105
#define IDM_EXIT                        105
#define IDS_COLUMN_FOLDER               106
#define IDS_COLUMN_ORIGINALSIZE         107
#define IDS_COLUMN_NEWSIZE              108
#define IDC_PEC2GUI                     109
#define IDS_FILESLV_STATUS_TEXT_1       110
#define IDS_ABOUTTEXT                   111
#define IDS_COLUMN_RATIO                112
#define IDS_PROJECT_BROWSE_TITLE        113
#define IDS_WATERMARK_BROWSE_TITLE      114
#define IDS_FIND_EXE_TITLE              115
#define IDS_NO_FILES_SELECTED           116
#define IDS_MESSAGEBOX_CAPTION          117
#define IDS_ERROR_LAUNCHING_PEWATERMARK 118
#define IDS_BACKUP_OF                   119
#define IDS_LAUNCHED                    120
#define IDS_CAPTION_TEST_RESULT         121
#define IDS_DID_WORK_OK                 122
#define IDS_COMPRESS_AGAIN              123
#define IDS_WATERMARK_ERROR             124
#define IDS_ERROR_LOADING_PROJECT       125
#define IDS_INPROGRESS                  126
#define IDS_RESOURCE_MODULE_ERROR       127
#define IDS_ERROR_STORING_PROJECT       128
#define IDD_PRIMARYDIALOG               129
#define IDS_COLUMN_ID                   129
#define IDI_ICON1                       130
#define IDS_COLUMN_NAME                 130
#define IDR_ITEMRCLICK                  131
#define IDS_DEVELTEK_ABOUTTEXT          131
#define IDS_SUPER_COMPRESS_WARNING      131
#define IDD_OPTIONS                     132
#define IDS_COLUMN_LV_INDEX             132
#define IDD_HOOKS                       133
#define IDS_COLUMN_LV_NAME              133
#define IDD_LOADER_VARIABLES            134
#define IDS_COLUMN_LV_TYPE              134
#define IDS_COLUMN_LV_VALUE             135
#define IDD_LANG_SELECT                 135
#define IDS_PROJECT_NOT_COMPATIBLE      136
#define IDS_GLOBAL_SETTINGS_WARNING     137
#define IDB_OVERLAY                     138
#define IDS_WAITING_FOR_TERMINATION     138
#define IDS_REGISTERED                  139
#define IDS_TRIALDAYS                   140
#define IDS_STUDENT                     141
#define IDS_XLATCREDIT                  142
#define IDS_ORDER                       143
#define IDS_LANG_SWITCH                 144
#define IDS_FILE_WRITE_ERROR            145
#define IDS_ERROR_OPENING_FILE          146
#define IDS_BATCH_FILE_SELECT_TITLE     147
#define IDS_ERROR_ACCESS                148
#define IDB_BITMAP1                     148
#define IDS_NO_DOTNET_DLLS              149
#define IDS_DOTNET_BETA_WARNING         150
#define IDS_DOTNET_DISABLED             151
#define IDS_NO_PE64                     152
#define IDS_ALREADY_PEC2_PACKED         153
#define IDS_TL_BETA_WARNING             154
#define IDS_ERROR_OPENING_PE            155
#define IDS_LOADER_HOST_NOT_FOUND       156
#define IDS_WARNING                     157
#define IDS_ED_WARNING                  158
#define IDS_KEEP_ED_HOW_TO              159
#define IDS_KEEP_ED_YOU_DID             160
#define IDS_OVERLAY_SIZE                161
#define IDS_BYTES                       162
#define IDS_ED_UNNECESSARY              163
#define IDS_INSTALLER_WARNING_LINE_0    164
#define IDS_INSTALLER_WARNING_LINE_1    165
#define IDS_SIGNED_WARNING              166
#define IDS_INVALID_PE                  167
#define IDS_COMMAND_LINE                168
#define IDS_PATH                        169
#define IDS_TRANSLATION_WARNING         170
#define IDS_PRODUCT_VERSION             171
#define IDS_GUI_VERSION                 172
#define IDS_INTERNAL_VERSION            173
#define IDS_ENGINE_VERSION              174
#define IDS_VERSION_CHECK               175
#define IDS_TT_FORCE_IAT_RESTORE        176
#define IDS_TT_TRUNCATELAST             177
#define IDS_TT_BACKUP                   178
#define IDS_TT_ALLOWSECURITYDIR         179
#define IDS_TT_ENFORCE_MEMORY_PROTECTION 180
#define IDS_TT_KEEPOVERLAY              181
#define IDS_TT_WINLOADER                182
#define IDS_TT_SKIPSHARED               183
#define IDS_TT_STRIPUNUSED              184
#define IDS_TT_STRIPFIXUPS              185
#define IDS_TT_CODEINTEGRITYCHECK       186
#define IDS_TT_COMPRESS_SAFE            187
#define IDS_TT_COMPRESS_EXPORTS         188
#define IDS_TT_MULTICOMPRESS            189
#define IDS_TT_AUTO_CHOOSE_CODEC        190
#define IDS_TT_DECODERTYPE              191
#define IDS_TT_SLIDER_COMPLEVEL         192
#define IDS_TT_RESTORE_DEFAULTS         193
#define IDS_TT_MAKEDEFAULT              194
#define IDS_TT_HOOKS                    195
#define IDS_TT_CODECS                   196
#define IDS_WL_SHOULD_MANDATE_WARNING   197
#define IDS_TT_TRIM_MEMORY              198
#define IDS_TT_SUPER_COMPRESS           199
#define IDS_TT_MAX_DECOMPRESS           200
#define IDS_COLUMN_TYPE                 201
#define IDS_TYPE_NETDLL                 202
#define IDS_TYPE_NETEXE                 203
#define IDS_TYPE_PE64DLL                204
#define IDS_TYPE_PE64EXE                205
#define IDS_TYPE_PE32DLL                206
#define IDS_TYPE_PE32EXE                207
#define IDS_TYPE_UNSUPPORTED            208
#define IDS_ALREADY_PACKED_UPX          209
#define IDS_ALREADY_PACKED_UNKNOWN      210
#define IDS_TT_STRIP_DEBUG_DIRECTORY    211
#define IDC_MARK                        1000
#define IDC_ADD                         1001
#define IDC_LANGUAGELIST                1001
#define IDC_FILESLIST                   1002
#define IDC_CODECCOMBO                  1002
#define IDS_UC_OK                       1002
#define IDC_CANCEL                      1002
#define IDC_SELECTFILES                 1003
#define IDC_REMOVE                      1003
#define IDS_UPDATE_AVAILABLE            1003
#define IDS_UPDATE_UNAVAILABLE          1004
#define IDS_ERROR_THREAD_NOT_RUNNING    1005
#define IDC_CODEC_SETTINGS              1006
#define IDS_ERROR_CANCELLED             1006
#define IDC_CODECS                      1007
#define IDS_ERROR_CONNECT_GENERAL       1007
#define IDC_COMPRESS                    1008
#define IDS_CONNECT_START               1008
#define IDC_TRIM                        1009
#define IDS_CONNECT_COMPLETE            1009
#define IDC_START                       1010
#define IDC_CODECLIST                   1010
#define IDS_STEP_DOWNLOAD_START         1010
#define IDC_SETTINGS                    1011
#define IDC_CODEC_NAME                  1011
#define IDC_HOOKS                       1011
#define IDS_STEP_DOWNLOAD_PROGRESS      1011
#define IDC_RESTORE_BACKUP              1012
#define IDC_CODEC_AUTHOR                1012
#define IDS_STEP_DOWNLOAD_COMPLETE      1012
#define IDC_TEST                        1013
#define IDS_SHOULDEXIT                  1013
#define IDS_WAITING                     1014
#define IDC_PROGRESS_CURRENT            1015
#define IDC_PROGRESS_TOTAL              1016
#define IDC_COMPRESS_EXPORTS            1016
#define IDC_STRIP_FIXUPS                1017
#define IDC_BACKUP                      1018
#define IDC_COMPRESS_RESOURCES          1019
#define IDC_SKIPSHARED                  1020
#define IDC_CODEINTEGRITYCHECK          1021
#define IDC_ENFORCE_MEMORY_PROTECTION   1022
#define IDC_LISTRESOURCES               1023
#define IDC_PRODUCT_VERSION             1024
#define IDC_GUI_VERSION                 1025
#define IDC_AUTHOR                      1026
#define IDC_SLIDERCOMPLEVEL             1027
#define IDC_HOOKLIST                    1029
#define IDC_HOOK_NAME                   1030
#define IDC_HOOK_AUTHOR                 1031
#define IDC_HOOKCOMBO                   1032
#define IDC_MAKEDEFAULT                 1033
#define IDC_REGTEXT                     1034
#define IDC_LOADER_AUTHOR               1034
#define IDC_WATERMARK                   1035
#define IDC_COMPLEVEL                   1036
#define IDC_KEEPOVERLAY                 1037
#define IDC_EMULATEOVERLAY              1038
#define IDC_OVERLAYBITMAP               1039
#define IDC_STRIPUNUSEDRESOURCES        1040
#define IDC_COMBOLOADER                 1041
#define IDC_LOADER_NAME                 1042
#define IDC_MULTICOMPRESS               1043
#define IDC_DECODER_TYPE                1045
#define IDC_VARIABLE_NAME               1046
#define IDC_VARIABLE_DESCRIPTION        1047
#define IDC_VARIABLE_DESCRIPTION2       1048
#define IDC_STRING_VALUE                1049
#define IDC_INTEGER_VALUE               1050
#define IDC_BOOLEAN_VALUE               1051
#define IDC_VARIABLES_LIST              1052
#define IDC_BUTTON1                     1054
#define IDC_LOADERVARIABLES             1054
#define IDC_UPDATE_VALUE                1054
#define IDC_EDIT1                       1055
#define IDC_ADDITIONALINFO              1055
#define IDC_AUTO_CHOOSE_CODEC           1058
#define IDC_ALLOWSECURITYDIR            1059
#define IDC_WINLOADER                   1060
#define IDC_VARIABLE_VALUE              1061
#define IDC_STRIP_DEBUG_DIRECTORY       1061
#define IDC_SLIDER1                     1062
#define IDC_TRUNCATELAST                1063
#define IDC_SUPER_COMPRESS              1064
#define IDC_BUTTON2                     1065
#define IDC_MAX_DECOMPRESSION_SPEED     1065
#define IDC_VERSIONINFO                 1066
#define IDC_FORCE_IAT_RESTORE           1068
#define IDC_TRIM_MEMORY                 1069
#define IDS_CANCEL                      9002
#define IDS_IGNORE                      9003
#define IDS_RETRY                       9004
#define IDS_ABORT                       9005
#define IDS_HELP                        9006
#define IDS_YES                         9007
#define IDS_NO                          9008
#define IDS_CONTINUE                    9009
#define IDS_DONOTASKAGAIN               9010
#define IDS_DONOTTELLAGAIN              9011
#define IDS_DONOTSHOWAGAIN              9012
#define IDS_YESTOALL                    9013
#define IDS_NOTOALL                     9014
#define IDS_TRYAGAIN                    9015
#define IDS_REPORT                      9016
#define IDS_IGNOREALL                   9017
#define IDS_SKIP                        9018
#define IDS_SKIPALL                     9019
#define IDM_RESTORE_BACKUP              32774
#define IDM_DELETE_SELECTED             32775
#define IDM_RUN_SELECTED                32776
#define IDM_SETTINGS                    32778
#define IDM_LOAD                        32783
#define IDM_SAVE                        32784
#define IDM_SAVE_AS                     32785
#define IDM_UPDATE                      32788
#define IDM_VISIT                       32789
#define IDM_GETWATERMARK                32794
#define IDM_COMPRESS                    32796
#define IDM_GETWATERMARKOFSELECTED      32798
#define IDM_REMOVE                      32802
#define IDM_TEST                        32806
#define IDM_BROWSE                      32808
#define IDM_LANG                        40004
#define IDM_DOCS2                       40005
#define IDM_SHOW_OUTPUT_LOGS            40007
#define ID_Menu                         40009
#define IDM_COPYCOMMANDLINE             40011
#define ID_ITEMMENU_CREATEBATCHFILETOCOMPRESSSELECTEDITEMS 40013
#define IDM_BATCHFILE                   40014
#define ID_ACTION_BUILDBATCHFILEFORSELECTEDITEMS 40015
#define ID_PROJECT_EXPORTPROJECTTOBATCHFILE 40016
